name: ChaosEdit
main: Chaos\ChaosEdit\Loader
author: Chaos
version: 1.0.0
api: 4.0.0
commands:
    /pos1:
        usage: //pos1 [x] [y] [z]
        permission: WE
    /pos2:
        usage: //pos2 [x] [y] [z]
        permission: WE
    /fill:
        usage: //fill [block]
        permission: WE
    /hollow:
        usage: //hollow [block]
        permission: WE
    /outline:
        usage: //outline [block]
        permission: WE
    /undo:
        usage: //undo [amount of space]
        permission: WE
    /replace:
        usage: //replace
        permission: WE
permissions:
    WE:
        default: op
